### ISSUE TITLE
Postgresql client

### ISSUE THREAD

**Issue by lpil** [gleam-lang/suggestions#1]
This OCaml library has a nice interface that would map well onto Gleam (minus the async)
https://medium.com/@bobbypriambodo/interfacing-ocaml-and-postgresql-with-caqti-a92515bdaa11

I would suggest we wrap epgsql
https://github.com/epgsql/epgsql

We would likely want to provide an easy to set up pool, perhaps this lib could provide some inspiration (not read the source yet). See also https://github.com/gleam-lang/suggestions/issues/2
https://github.com/egobrain/epgpool

**Comment by lpil** [comment]
https://github.com/gleam-lang/gleam_experimental_epgsql

**Comment by CrowdHailer** [comment]
https://github.com/midas-framework/midas/tree/master/src/pg_client
