### ISSUE TITLE
Provide Dockerfile example 

### ISSUE THREAD

**Issue by michaeljones** [gleam-lang/suggestions#106]
When working with Elixir & Phoenix, I found the example Dockerfile in the Phoenix docs (https://hexdocs.pm/phoenix/releases.html#containers) to be enormously useful. I think it might be reasonable to maintain a similar one for Gleam either in the docs or perhaps in the echo server repo? 

I realise Docker might be considered a stretch for language docs so it is understandable not to include it but I imagine it would be useful for beginners like me that are trying to get going with Gleam apps. (Though at the moment my experience is mostly with working on random bits of the toolchain more than writing & deploying Gleam apps.)

**Comment by lpil** [comment]
We will want this at some point, but we will need work out the build / release tooling and documentation first I think. For now it's best to use the Erlang rebar3 documentation I think.

**Comment by lpil** [comment]
Having said that it would be grand to have this in the echo server example, as you've said!

**Comment by michaeljones** [comment]
My first attempt at this is here: https://github.com/gleam-lang/example-echo-server/pull/9

**Comment by lpil** [comment]
Is that enough to close this issue? I would like to later have a section on deployment on the website.

**Comment by michaeljones** [comment]
I think it certainly makes sense to link to that example from somewhere on the website related to deployment or releases. I can do that at some point. Don't mind if we use this ticket or another.

**Comment by lpil** [comment]
Thanks Michael!!
