### ISSUE TITLE
Association Lists

### ISSUE THREAD

**Issue by varnerac** [gleam-lang/suggestions#109]
OCaml's association lists seem like a good fit for the standard library. Would we put them in the `List` module like OCaml or in their own module like Erlang's `proplists`?

**Comment by varnerac** [comment]
I guess there are a couple of functions already in the List module for 2-element tuples, so that's the spot.

**Comment by lpil** [comment]
For sure! If there's any specific functions missing we can add them to the list module with the existing ones.

**Comment by lpil** [comment]
I'll close this as there's nothing specific to do here, but any additional functions for proplists will be gratefully accepted
