### ISSUE TITLE
Function composition operator

### ISSUE THREAD

**Issue by sporto** [gleam-lang/suggestions#113]
Function composition feels quite verbose currently.

e.g.
```
things
|> list.map(
  string.trim
  |> function.compose(string.replace(_, ",", ""))
  |> function.compose(int.parse)
)
```

It would be nice to have an operator to make something like this more succint and readable e.g.

```
things
|> list.map(
  string.trim
  >> string.replace(_, ",", "")
  >> int.parse
)
```

Thanks

**Comment by lpil** [comment]
No plans to add more function operators as they're difficult for newcomers to understand or look up. 

Less importantly I also feel that there's a lot of overlap between a composition operator and the pipe application operator, I've not seen an example where one could not be rewritten into the other clearly.

The given example can be written more concisely like so:

```rust
things
|> list.map(fn(s) {
  string.trim(s)
  |> string.replace(",", "")
  |> int.parse
})
```

**Comment by lpil** [comment]
Going to close this as we don't have any clear way to move forwards, and the pipe operator alternative can be used.

I would be open to proposals for enhancements to making anonymous functions with the pipe operator more consise.
