### ISSUE TITLE
Sourcemaps, ala Javascript

### ISSUE THREAD

**Issue by JeffreyBenjaminBrown** [gleam-lang/suggestions#143]
See the [issue of the same name](https://github.com/gleam-lang/gleam/issues/1268) on the gleam-lang issue tracker.

**Comment by JeffreyBenjaminBrown** [comment]
Sorry, tried to search and instead created this issue.

**Comment by lpil** [comment]
Closing this in favour of the other issue as this is something we want to do for sure. Thanks
