### ISSUE TITLE
Command for `run`

### ISSUE THREAD

**Issue by djKooks** [gleam-lang/suggestions#18]
Hello
First, thanks for great project.

Currently, seems that there are only `build` command to make `.erl` file, and no command for running the module directly. 

For example, new project with `gleam new`, I sometimes just want to make console print message in `hello_world()` just using single command.
```
pub fn hello_world() {
  "Hello, from first_project!"
}
```

Is there a plan to make such thing?

**Comment by lpil** [comment]
Hi! Thanks for trying Gleam.

We defer to the standard Erlang build tool rebar3 for all aspects of interacting with Gleam projects, so we're limited by what they offer there. As far as I'm aware the recommended ways to run Erlang code with rebar3 is to call the function from the [shell](https://www.rebar3.org/docs/commands#section-shell), to create an [escript](https://www.rebar3.org/docs/commands#section-escriptize), or to create a [release](https://www.rebar3.org/docs/releases). It may be worth opening a ticket in their [issue tracker](https://github.com/erlang/rebar3/issues) if you have need for more.

I do think it would be handy to have more control over the compiling and running of Gleam code. Once the language is more mature and higher priority work has been completed we may create our own build tool that address these problems.

**Comment by djKooks** [comment]
@lpil thanks for your comment~
