### ISSUE TITLE
Extendible or overlapping enums

### ISSUE THREAD

**Issue by lpil** [gleam-lang/suggestions#24]
```rust
enum Role {
  Teacher
  Student
}

enum SchoolPerson {
  Janitor
} + Role
```

```rust
type Role = enum {
  Teacher
  Student
};

type SchoolPerson = enum Role + {
  Janitor
}
```

Gleam has no subtyping, so is this useful? It would remove some boilerplate but doesn't make the language more expressive.

**Comment by OvermindDL1** [comment]
For note, OCAML supports these like:

Extendable Enum's (Extendable Variants):
```ocaml
(* Define the extendable variant name with `..` *)
type ext_things = ..

(* Add heads to it one at a time like: *)
type ext_things += Nope

(* Or add many at a time:
type ext_things +=
| Int of int
| String of string
```

OCaml actually has two built-in 'global' names for some extendable variants, the first is `exn`, which holds all exceptions (yes exceptions in OCaml are just a global extendable variant), you can make a 'new' exception by just extending it:
```ocaml
type exn += MyExceptionalType of Blah
```

And the second is the polymorphic variant, which is the 'unnamed' extendable variant.  They are created on demand.  They are just a normal head but prefixed with \`, and can be used like:
```ocaml
let blah = function
| `Int i -> string_of_int i
| `Float f -> string_of_float f
| `String s -> s
```
This `blah` function accepts a Closed set of polymorphic variants, the type of `blah` will be `[< `Float of float | `Int of int | `String of string ] -> string`, where the `<` means it is closed, so it *must* be one of these types (or it won't compile).  Consequently an open one would be like:
```ocaml
let blah = function
| `Int i -> string_of_int i
| `Float f -> string_of_float f
| `String s -> s
| _ -> "<Unknown>"
```
Which gets the type of `[> `Float of float | `Int of int | `String of string ] -> string`, the `>` meaning open, so it will accept any of these types directly and work on them but it will also accept all others with a fallback.

Polymorphic is special in that you can constrain the types it is allowed to accept, where if you don't have the `_ -> ...` fallback case for extendable variants then you get the all famous warning 8:
```ocaml
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a case that is not matched:
*extension*
Matching over values of extensible variant types (the *extension* above)
must include a wild card pattern in order to be exhaustive.
val blah : ext_things -> string = <fun>
```
Internally polymorphic variants are just extendable variants but without a name, so they are 'global scope', in addition to the above typing nicities.

OCaml specifically does not have a method of making a new type containing the types of another as it breaks names (made the names non-specific), thus the traditional method is to just wrap the other type in a head of your type:
```ocaml
type something0 =
| Int of int
| Float of float

type something1 =
| Something0 of something0
| String of string
```
Or just use an extensible variant.

The reason OCaml doesn't allow copying heads is that heads need to be unique in scope to be able to reference them.  I've always been of the opinion that something like `something0::Int` or so would have been a useful distinguisher that would fix it though, but as it stands if you could 'extend' `something1` from `something0` above, then when you go to match on `Int i` it doesn't know which type it must require.

**Comment by michallepicki** [comment]
Not sure if this belongs here (and maybe it's already supported but I couldn't find info in docs?) but for overlapping Enums, I'd like to be able to use constructors from other types. To make them work maybe a name alias could be required. Something like:
```
Enum MyEnum {
  Data(Int, String) ~ struct(Int, String)
  Approximation ~ Float
  Whatever
}
```

These aliased types would compile to the same target representation. Inside the module where such MyEnum is defined, and wherever MyEnum is imported, an easy conversion from Approximation to Float is allowed (and the opposite). That would be using some explicit syntax or done implicitly, I don't know.

**Comment by lpil** [comment]
If enums are untagged it's not possible to always pattern match on them as without the tag we can't tell the difference between two values with the same runtime representation. i.e.

```rust
external type TimeoutSeconds // int()
external type Dollars // int()
```

This is the same situation as with Elixir and it's structs and protocols.

**Comment by michallepicki** [comment]
So I can do this by declaring things as `external type`s and using `identity` all over the place

**Comment by lpil** [comment]
You can but you'd have to be very careful as using identity to perform unsafe coersions is not type checked. I would lean towards keeping the Gleam code well typed and doing any dynamically typed programming in Erlang.

**Comment by michallepicki** [comment]
Not sure how useful that is, but I found a paper where the [CDuce](https://www.cduce.org/) people propose a different approach for implementing polymorphic variants than the one OCaml used: https://www.irif.fr/~gc/papers/icfp16.pdf

They even published an interactive tool to play with: https://www.cduce.org/ocaml/

I also found a few languages built around polymorphic variants / row polymorphism, maybe their implementations also could be useful: MLPolyR and ordo

**Comment by lpil** [comment]
That's great, thank you

**Comment by sporto** [comment]
Related to this, this Elm proposal is a good read https://shuangrimu.com/posts/elm-extensible-unions.html#what-are-extensible-union-types
