### ISSUE TITLE
Warn for unreachable case branches

### ISSUE THREAD

**Issue by michallepicki** [gleam-lang/suggestions#26]
The most common mistake I make when writing Gleam is typing true or false instead of True or False when pattern matching :man_facepalming: . This compiles just fine but silently fails because e.g. when false is first, it always matches and binds the value to first.

Basic cases of this, i.e. where a catch-all pattern is not at the last position, could be caught at compile time and show a warning.

**Comment by michallepicki** [comment]
I guess Erlang may be warning about unused variables, so this is not a big problem, but handling this even earlier in Gleam could make for an even better experience - in my case I didn't notice the Erlang warnings :man_facepalming:

**Comment by lpil** [comment]
This is definitely wanted! There is an issue to track this feature here -> https://github.com/gleam-lang/gleam/issues/34
