### ISSUE TITLE
Templating language

### ISSUE THREAD

**Issue by lpil** [gleam-lang/suggestions#3]
- Built at compile time
- Plugin based escaping (supply no escaping, xml/html)
- Logic-less?

**Comment by gamebox** [comment]
Logic-less is nice if you mean something like mustache.  An idea is to have something really nice like [Scala Play's Twirl](https://www.playframework.com/documentation/2.7.x/ScalaTemplates).  It compiles the template to a Scala file and allows you to have full type safety, parameterized partials, and more.

**Comment by lpil** [comment]
Thank you for the recommendation!

**Comment by nono** [comment]
See https://github.com/gleam-lang/gleam/issues/565

**Comment by lpil** [comment]
Thanks @nono
