### ISSUE TITLE
UUID generation library

### ISSUE THREAD

**Issue by lpil** [gleam-lang/suggestions#35]

**Comment by MainShayne233** [comment]
i started to take a crack at this, and got to the part where i'd want to ask the OS for the current time. is the a capability `gleam` currently facilitates?

**Comment by lpil** [comment]
Not built in, we would need to import an external Erlang function and use that

**Comment by rvcas** [comment]
https://github.com/rvcas/ids/blob/main/src/ids/uuid.gleam#L16

this now supports version 4 uuids

**Comment by lpil** [comment]
Nice. I guess we can close this :)
