### ISSUE TITLE
Regex library

### ISSUE THREAD

**Issue by lpil** [gleam-lang/suggestions#40]

**Comment by eterps** [comment]
Do we want regex support to be added to stdlib? https://github.com/eterps/stdlib/commit/d587829f318c6374235cddaaf03b73169033a7eb

I am assuming we want to lean on Erlang's PCRE implementation for now?

What functions do we want at first? `match`, `replace` & `split`?

Any thoughts on preferred argument order?

**Comment by CrowdHailer** [comment]
Is this done with the addition to stdlib?

**Comment by eterps** [comment]
No, I am working on a next PR. And a final one after that.

**Comment by CrowdHailer** [comment]
Let me know if you want any help or just eye-balls. I was looking into Regex for a problem I had yesterday. For that problem I might be getting by with binary.split and multiple patterns for now.

**Comment by eterps** [comment]
> Let me know if you want any help or just eye-balls.

Thanks, I'd appreciate that. See: https://github.com/gleam-lang/stdlib/pull/83 for the next one.

In the final PR I'd like to add replace & substitute functionality (only on first occurence or globally and by defining a string pattern or a replacement function).

Also note that @lpil suggested that he might revise the regex API later: https://github.com/gleam-lang/stdlib/pull/80#pullrequestreview-434424703
