### ISSUE TITLE
Bring back record / struct type

### ISSUE THREAD

**Issue by sporto** [gleam-lang/suggestions#47]
I guess this has already been discussed, but it appears that to declare a record type I need to use a custom type like:

```
pub type Cat {
  Cat(name: String, cuteness: Int)
}
```

When I wish I could do

```
pub type Cat {
  name: String,
  cuteness: Int
}
```

If custom types are really needed, maybe there could be some sugar that expands to that

**Comment by sporto** [comment]
hmm, found this https://github.com/gleam-lang/gleam/issues/355

Found this odd as I expected someting similar to similar functional languges, etc, 
It took me a while to understand how to declare a struct from the Gleam docs.
But maybe is just a matter of getting used to this.

**Comment by lpil** [comment]
That's right, a custom type with a single constructor and struct are the same thing! Before we had 2 syntaxes that were functionally identical so we merged them into one.

I agree, the docs could be improved. This will come with time. Thank you

**Comment by lpil** [comment]
Sorry about the delay btw, not sure how I missed this one

**Comment by sporto** [comment]
Say that you have

```
pub type Animal {
  Cat(name: String, cuteness: Int)
}
```

Then in my code I use `.name` for accessing the field.

But then someone adds another variant

```
pub type Animal {
  Cat(name: String, cuteness: Int)
  Dog(...)
}
```

All code using `.name` will be broken, right? 
It is not obvious for the person adding the variant that this will happen. This concerns me.

**Comment by lpil** [comment]
Yes, that's right. The compiler will make it clear that this is a breaking change, and experienced users will understand the consequences of this change to the data structure.
