### ISSUE TITLE
proc_lib wrapper

### ISSUE THREAD

**Issue by lpil** [gleam-lang/suggestions#53]
For creation of OTP compatible processes

**Comment by CrowdHailer** [comment]
Is this something you want to develop within Standard Lib? Or is process architecture something that you would like to experiment with in libraries

**Comment by lpil** [comment]
Not within the standard library, it would be a hex package. I'm mostly interested in whether an abstraction could be built around proc lib that allows us to make use of it without Erlang glue code.

**Comment by CrowdHailer** [comment]
I am keen to hear about efforts in this area. And help out as I can.
I think wrapping proc_lib is probably a good level to interface with erlang functionality. 

I've made some efforts on a process library here https://github.com/did-app/midas/blob/master/src/process/process.gleam.
It's internal to my project now so I can iterate rapidly, but could be inspiration/base of how to do it.

Currently, I'm using the raw spawn_link functions but I think when I want to make everything work with beam debugging most of it will be switched to `proc_lib`

**Comment by lpil** [comment]
Some prior art: https://github.com/fishcakez/core

**Comment by CrowdHailer** [comment]
I think  this issue should be renamed to  "create a process library".
I'm no longer sure proc_lib is the right abstraction level. you might want a mix of `proc_lib` and `gen`, or to go lower.

**Comment by lpil** [comment]
I don't think so, the important part of this library is that is OTP compatible, so it would be the Gleam module version of proc_lib.

**Comment by lpil** [comment]
@CrowdHailer after a bunch more thinking I think you'd given me another perspective on this. I'm going to close this issue and mull it over some more. Thanks!

**Comment by CrowdHailer** [comment]
No worries, it's a very interesting problem. Gleam gives you so much power, I want to change how I do quite alot of things, when compared to OTP. However that very choice means less relying on existing libraries.
