### ISSUE TITLE
Gleam community building

### ISSUE THREAD

**Issue by rjdellecese** [gleam-lang/suggestions#54]
At the moment there are, to my knowledge, primarily two places (excepting GitHub) in which  conversations about Gleam happen on the internet: 1) [the IRC channel](https://webchat.freenode.net/#gleam-lang), and 2) [this Elixir Forum thread](https://elixirforum.com/t/gleam-a-statically-typed-language-for-the-erlang-vm/20349). Neither of these seem like great solutions for the people who discover Gleam and then want to learn more/build things/express their interest and excitement/collaborate on Gleam projects or project ideas.

What are some better options? The first ones that came to mind were Slack, Discord, and Discourse, and I think any of those might be great. Another option which might be a good compromise between the aforementioned is [Spectrum](https://spectrum.chat/about), which was apparently [bought by GitHub](https://spectrum.chat/spectrum/general/spectrum-is-joining-github~1d3eb8ee-4c99-46c0-8daf-ca35a96be6ce) ~1.5 years ago.

I think that any solution that is **more accessible than IRC** and **more Gleam-centric** than the Elixir Forum would be a big win for growing the Gleam community and garnering excitement for the Gleam language!

**Comment by CrowdHailer** [comment]
I've never really got into IRC. Probably came to programming to late. It does seem weird to me that there is no history etc etc. 
However I have had luck using matrix to access the IRC channel. Perhaps suggesting people not that familiar with IRC use riot.im. There are things not to like about it but it has a familiar email password login, and keeps history once you have signed in.

**Comment by lpil** [comment]
I struggled to get riot to work for me, none of the buttons seemed to work. I'll have to try it again.

**Comment by lpil** [comment]
I've opened a Discord server! Hooray! https://discord.gg/x6GFbVn
