### ISSUE TITLE
Random number / value generation library

### ISSUE THREAD

**Issue by lpil** [gleam-lang/suggestions#56]
https://github.com/gleam-lang/stdlib/issues/32

**Comment by NicklasXYZ** [comment]
Just noticed this, just now.
Maybe this works: https://nicklasxyz.github.io/gleam_stats/gleam_stats/generators/ :)?

**Comment by lpil** [comment]
Hey cool! Would you like to add it to https://github.com/gleam-lang/awesome-gleam ?

**Comment by NicklasXYZ** [comment]
Yes, I will do so when I get the chance :smiley:

**Comment by lpil** [comment]
Thank you
