### ISSUE TITLE
JSON library

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/suggestions#59]
This is more than one way to do this. I see two stages.

### Stage one
Probably wrapping an erlang library, there is a encode/decode function that takes an ugly general JSON type. 

### Stage two
Have a way of specifying a type to a JSON spec, similar to serde in rust.

I don't know the erlang ecosystem, can someone suggest good JSON libraries and I can work on step one

**Comment by lpil** [comment]
There's one here -> https://github.com/rjdellecese/gleam_jsone

Probably need to add this to the awesome-gleam list.

**Comment by CrowdHailer** [comment]
+1 for adding to the awesome gleam list
