### ISSUE TITLE
Parameterised modules

### ISSUE THREAD

**Issue by lpil** [gleam-lang/suggestions#67]
An idea for codegen from Jose that is similar to protocols.

```
    defparammod Greeter do
      defcontract greeting()

      def say do
        IO.puts greeting()
      end
    end

which you will implement it as:

    defimpl HelloWorld, from: Greeter do
      defp greeting do
        "Hello world"
      end
    end

this will generate the modules:

    defmodule Greeter do
      def __obfuscated_say(greeting) do
        IO.puts greeting.()
      end
    end

    defmodule HelloWorld do
      def say do
        Greeter.__obfuscated_say(&greeting/0)
      end

      defp greeting do
        "Hello world"
      end
    end
```

**Comment by CrowdHailer** [comment]
What's the usecase for these, is it to enable working with behaviours?
Is there any way this can be used to make "things" sendable/not sendable?

**Comment by lpil** [comment]
This would be one option for how we would do codegen for traits/module functors/type classes.

It's not directly linked to making things sendable etc but the language features listed above could be used to accomplish that.
