### ISSUE TITLE
Add a type to represent free form (not utf8) binaries

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/suggestions#72]
I'm not sure how to tackle this best. 

- A String can always be treated as a Binary but not the reverse.
- How often do people work with raw binaries, is there a future where there would be syntax to create them e.g. `<0,2>` & `<"Foo">`

My feeling is that we should add add a Binary type and binary module to standard lib.
My suggestion would be to mostly ignore any cleverness in treating Strings as binaries and just have a function `binary.from_string` for cases when it matters. e.g. 
```
let has = sha256(binary.from_string("foo"))
```

We probably have to make at least some start in this area before we can add a module for base encoding and decoding, because the results of decoding are not a utf8 string.

**Comment by CrowdHailer** [comment]
https://github.com/gleam-lang/stdlib/pull/59

**Comment by lpil** [comment]
Love it, thank you!
