### ISSUE TITLE
Http client

### ISSUE THREAD

**Issue by lpil** [gleam-lang/suggestions#8]

**Comment by MainShayne233** [comment]
Thoughts on trying to build out a lower-level base library like [mint](https://github.com/elixir-mint/mint) to build higher level HTTP clients on top of?

**Comment by lpil** [comment]
Sounds good, though I would prefer to not use any Elixir libraries as they are difficult to use from non-Elixir projects and core Gleam libraries should not pull in the Elixir compiler and standard library.

**Comment by MainShayne233** [comment]
++ agreed! The proposal was more aimed at taking a similar approach to mint (low-level base library to build on top of) versus using it directly.

**Comment by lpil** [comment]
https://github.com/gleam-experiments/httpc
