### ISSUE TITLE
Formatter should add brackets when piping into one arity function.

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/suggestions#81]
```rust
"something"
|> Ok()

"something"
|> Ok
```

Both of these are left alone by the formatter.  I think for consistency one should be preferred.

My choice would be **with** brackets but I don't have a strong opinion

**Comment by lpil** [comment]
I'd like to taller the more common approach and not use parens. As far as I know Elixir is the only language that uses parens here.

Additionally when parens are added what is happening is more ambiguous. There are two ways the pipe can be rewritten with parens, while there is only one without, so without is more clear to the reader.
