### ISSUE TITLE
Github syntax highlighting and codebase detection

### ISSUE THREAD

**Issue by hhandoko** [gleam-lang/suggestions#90]
It would be great if we could have syntax highlighting for Gleam source code in Github, making it easier to review code.

I found some instructions here:
* Adding a new language (incl. grammar): https://github.com/github/linguist/blob/master/CONTRIBUTING.md
* Adding a new language for codebase detection: https://github.com/github/linguist/blob/master/lib/linguist/languages.yml

These will also help enable proper detection of Gleam codebases within Github, as Gleam codebases show up as Erlang at the moment.

**Comment by lpil** [comment]
A grand idea! We're already tracking this here -> https://github.com/gleam-lang/gleam/issues/477

I'm not sure we qualify for inclusion yet but if someone would like to try that would be much appreciated.
