### ISSUE TITLE
Compile to JavaScript

### ISSUE THREAD

**Issue by CrowdHailer** [gleam-lang/suggestions#95]
What are the technical obstacles to making it possible to compile Gleam to JavaScript?
Is it worth doing?

I think this would be an interesting thing to look at to find out Does Gleam have any unspoken assumptions based on the fact it is running on erlang? are these a good or a bad thing.

Now that new gleam projects come with OTP, which is great, I think it's likely there are more assumptions been made about how Gleam runs.

### What is the best approach to take.

- compile gleam to erlang to js somehow lumen
- compile Gleam to js, I like this because currently gleam produces readable erlang and producing readable javascript could be nice too
- compile Gleam to wasm, get's gleam in the browser but I'm not sure what advantages it has.

I am interested in making this happen, but could use some pointers to getting started.

**Comment by lpil** [comment]
I've also been interested in this, though I've not put much design into this yet. There's no particular reason why Gleam must target only Erlang.

Related: https://github.com/gleam-lang/gleam/pull/840
