### ISSUE TITLE
Warnings from dependencies shouldn't appear

### ISSUE THREAD

**Issue by sharno** [gleam-lang/suggestions#97]
I was building `cowboy` and this warning message appeared:
```

warning: Unused constructor
  ┌─ \\?\C:\Users\sharno\projects\cowboy\_build\default\lib\gleam_http\src\gleam\http\middleware.gleam:1:55
  │
1 │ import gleam/http.{Delete, Patch, Post, Put, Request, Response, Service}
  │                                                       ^^^^^^^^

The constructor Response is never used, it can be safely removed.
```

I think warnings from dependencies shouldn't appear for the package being built?

**Comment by CrowdHailer** [comment]
I sort of like that dependency warnings do show. Though I could be persuaded either way.

For the particular example shared above I like that it's probably the easiest thing to fix in gleam_cowboy and therefore highlighted as a nice first contribution for someone.

**Comment by lpil** [comment]
In future deps will only be compiled once, so the warning will be shown only that first time like in Elixir. I think this will be a good fit for this.
